---
- name: installing basic k8 setup on all nodes
  hosts: all
  become: True
  tasks:
  - name: installing initial
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
      br_netfilter
      EOF

      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
      sudo sysctl --system
  - name: open firewall ports on all nodes
    shell: |
      firewall-cmd --permanent --add-port=6443/tcp
      firewall-cmd --permanent --add-port=2379-2380/tcp
      firewall-cmd --permanent --add-port=10250/tcp
      firewall-cmd --permanent --add-port=10251/tcp
      firewall-cmd --permanent --add-port=10252/tcp
      firewall-cmd --permanent --add-port=10255/tcp
      firewall-cmd --reload
  - name: disable swap
      lineinfile:
        path: /etc/fstab
        regexp: "/dev/mapper/cl-swap     swap                    swap    defaults        0 0"
        line: "#/dev/mapper/cl-swap     swap                    swap    defaults        0 0"
        state: present
        backup: yes
  # name: restart docker-ce and containerd
   # service:
    #  name:
     # - docker
      #- containerd
      #status: started
      #enabled: True
  - name: add Kubernetes repo
    shell: |
      sudo swapoff -a
      cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
      EOF
      sudo setenforce 0
      sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
      sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
      sudo systemctl enable --now kubelet
      sudo systemctl restart containerd
      sudo systemctl restart docker
      sudo systemctl restart kubelet
      
